name: CI/CD

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Validar scripts e manifests
        run: |
          chmod +x scripts/*.sh
          bash scripts/test.sh
